#!/usr/bin/perl -w

my ($a, $b) = ("", "");

for (0..255) { $a .= chr($_) }
for (0..126) { $b .= $a }

### $b =~ s/([\\'])/\\$1/g;
### $b = "'$b'";

print length $b, "\n";
if ($b =~ /^'(\\\\|\\'|[^\\'])*'$/si) { print "yes\n"; }

