#!/usr/bin/perl -w

#
# Just a quick example that shows that you can use errstr to get the
# errors and dump_records to list all fields.
#

use strict;
use XBase;

my $tablename = "jezek";
$tablename = shift if @ARGV;

my $table = new XBase($tablename) or die XBase->errstr();
$table->dump_records() or die $table->errstr();
$table->close() or die $table->errstr();

