#!/usr/bin/perl -w

use strict;
use DBI;

my $dbh = DBI->connect("dbi:XBase:t") or die $DBI::errstr;
my $sth = $dbh->prepare("select facility,roomname from rooms where
facility = 'Audio' or roomname > 'B'") or die $dbh->errstr();
$sth->execute() or die $sth->errstr();

my @line;
while (@line = $sth->fetchrow_array())
	{ print "@line\n"; }

$sth->execute() or die $sth->errstr();
my $lineref;
while ($lineref = $sth->fetchrow_arrayref())
	{ print "@$lineref\n"; }


__END__

